/**
 * Itinerary Days Controller
 *
 * REST API endpoints for itinerary day management.
 * Nested under /itineraries/:itineraryId/days
 */

import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  HttpCode,
  HttpStatus,
} from '@nestjs/common'
import { ApiTags } from '@nestjs/swagger'
import { ItineraryDaysService } from './itinerary-days.service'
import type {
  ItineraryDayResponseDto,
  ItineraryDayWithActivitiesDto,
  CreateItineraryDayDto,
  UpdateItineraryDayDto,
  ReorderDaysDto,
  AutoGenerateDaysDto,
  BatchCreateDaysDto,
} from '@tailfire/shared-types'

@ApiTags('Itinerary Days')
@Controller('itineraries/:itineraryId/days')
export class ItineraryDaysController {
  constructor(private readonly daysService: ItineraryDaysService) {}

  /**
   * Get all days for an itinerary
   * GET /itineraries/:itineraryId/days
   */
  @Get()
  async findAll(
    @Param('itineraryId') itineraryId: string
  ): Promise<ItineraryDayResponseDto[]> {
    return this.daysService.findAll(itineraryId)
  }

  /**
   * Get all days with nested activities
   * GET /itineraries/:itineraryId/days/with-activities
   */
  @Get('with-activities')
  async findAllWithActivities(
    @Param('itineraryId') itineraryId: string
  ): Promise<ItineraryDayWithActivitiesDto[]> {
    return this.daysService.findAllWithActivities(itineraryId)
  }

  /**
   * Auto-generate days from trip dates
   * POST /itineraries/:itineraryId/days/auto-generate
   */
  @Post('auto-generate')
  async autoGenerate(
    @Param('itineraryId') itineraryId: string,
    @Body() dto: Omit<AutoGenerateDaysDto, 'itineraryId'>
  ): Promise<ItineraryDayResponseDto[]> {
    return this.daysService.autoGenerate({
      itineraryId,
      includePreTravelDay: dto.includePreTravelDay,
    })
  }

  /**
   * Reorder days (drag-and-drop)
   * PUT /itineraries/:itineraryId/days/reorder
   */
  @HttpCode(HttpStatus.OK)
  @Post('reorder')
  async reorder(
    @Param('itineraryId') itineraryId: string,
    @Body() dto: ReorderDaysDto
  ): Promise<ItineraryDayResponseDto[]> {
    return this.daysService.reorder(itineraryId, dto)
  }

  /**
   * Batch create multiple days
   * POST /itineraries/:itineraryId/days/batch
   *
   * Creates multiple days at once. Supports two modes:
   * - Count mode: Creates N days (1-30), continuing date sequence if last day has a date
   * - Date range mode: Creates a day for each date in the range
   *
   * Returns 400 for:
   * - "Batch limit exceeded (max 30 days)"
   * - "Either count or startDate/endDate must be provided"
   * - "Date range must start after last day (YYYY-MM-DD)"
   * - "Date range must be within trip dates"
   */
  @Post('batch')
  async batchCreate(
    @Param('itineraryId') itineraryId: string,
    @Body() dto: BatchCreateDaysDto
  ): Promise<ItineraryDayResponseDto[]> {
    return this.daysService.batchCreate(itineraryId, dto)
  }

  /**
   * Find or create a day by date
   * POST /itineraries/:itineraryId/days/find-or-create-by-date
   *
   * Finds an existing day with the given date, or creates one if not found.
   * Used for adding activities (like cruises) that have a specific date.
   */
  @Post('find-or-create-by-date')
  async findOrCreateByDate(
    @Param('itineraryId') itineraryId: string,
    @Body() dto: { date: string }
  ): Promise<ItineraryDayResponseDto> {
    return this.daysService.findOrCreateByDate(itineraryId, dto.date)
  }

  /**
   * Create a new day
   * POST /itineraries/:itineraryId/days
   */
  @Post()
  async create(
    @Param('itineraryId') itineraryId: string,
    @Body() dto: Omit<CreateItineraryDayDto, 'itineraryId'>
  ): Promise<ItineraryDayResponseDto> {
    return this.daysService.create({
      ...dto,
      itineraryId,
    })
  }

  /**
   * Get a single day by ID
   * GET /itineraries/:itineraryId/days/:id
   */
  @Get(':id')
  async findOne(@Param('id') id: string): Promise<ItineraryDayResponseDto> {
    return this.daysService.findOne(id)
  }

  /**
   * Update a day
   * PATCH /itineraries/:itineraryId/days/:id
   */
  @Patch(':id')
  async update(
    @Param('id') id: string,
    @Body() dto: UpdateItineraryDayDto
  ): Promise<ItineraryDayResponseDto> {
    return this.daysService.update(id, dto)
  }

  /**
   * Delete a day (cascade deletes all activities)
   * DELETE /itineraries/:itineraryId/days/:id
   */
  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  async remove(@Param('id') id: string): Promise<void> {
    return this.daysService.remove(id)
  }
}
