/**
 * Itinerary Days API Types
 *
 * TypeScript definitions for itinerary day management endpoints.
 * Shared between API (NestJS) and client (React/Next.js).
 */

// =============================================================================
// Response DTOs
// =============================================================================

/**
 * Itinerary Day Response DTO
 * Represents a single day within an itinerary
 */
export type ItineraryDayResponseDto = {
  id: string
  itineraryId: string
  dayNumber: number // 0 for pre-travel, 1+ for actual trip days
  date: string | null // ISO date string (nullable for date-flexible trips)
  title: string | null
  notes: string | null
  sequenceOrder: number
  createdAt: string
  updatedAt: string
}

/**
 * Itinerary Day with Activities
 * Includes nested activities for full day display
 */
export type ItineraryDayWithActivitiesDto = ItineraryDayResponseDto & {
  activities: ActivityResponseDto[]
}

// Import activity type (defined in activities.types.ts)
import type { ActivityResponseDto } from './activities.types'

// =============================================================================
// Request DTOs
// =============================================================================

/**
 * Create Itinerary Day DTO
 * Data required to create a new day
 */
export type CreateItineraryDayDto = {
  itineraryId: string
  dayNumber: number
  date?: string | null // ISO date string
  title?: string | null
  notes?: string | null
  sequenceOrder?: number
}

/**
 * Update Itinerary Day DTO
 * All fields optional for PATCH operation
 */
export type UpdateItineraryDayDto = {
  dayNumber?: number
  date?: string | null
  title?: string | null
  notes?: string | null
  sequenceOrder?: number
}

/**
 * Reorder Days DTO
 * Used for drag-and-drop reordering
 */
export type ReorderDaysDto = {
  dayOrders: Array<{
    id: string
    sequenceOrder: number
  }>
}

/**
 * Auto-Generate Days DTO
 * Creates days based on trip start/end dates
 */
export type AutoGenerateDaysDto = {
  itineraryId: string
  includePreTravelDay?: boolean // Whether to create day 0
}

/**
 * Batch Create Days DTO
 * Creates multiple days at once - supports both count mode and date range mode
 */
export type BatchCreateDaysDto = {
  /** Number of days to create (1-30). If last existing day has a date, continues the sequence. */
  count?: number
  /** Start date for date range mode (ISO string YYYY-MM-DD). Creates days for each date in range. */
  startDate?: string | null
  /** End date for date range mode (ISO string YYYY-MM-DD). Required if startDate is provided. */
  endDate?: string | null
  /** Where to insert new days. 'start' prepends and renumbers existing days. Defaults to 'end'. */
  position?: 'start' | 'end'
}
